# Generated by Django 6.0.1 on 2026-03-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='Enter the full name', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default='upload the file', upload_to='resumes/'),
        ),
    ]
