# Generated by Django 6.0.1 on 2026-03-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_full_name_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='NOT NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(default='NOT NULL', upload_to='resumes/'),
        ),
    ]
